/*!
 * Copyright (c) 2020 Digital Bazaar, Inc. All rights reserved.
 */
import { describe, it, expect } from 'vitest'
import { Ed25519VerificationKey2020 } from '../../src/index.js'
import * as jose from 'jose'

describe('compatibility', () => {
  describe('jose lib roundtrip import/export', () => {
    it('should round-trip to and from jose', async () => {
      // generated by 'jose' lib via `await jose.exportJWK(await jose.generateKeyPair('EdDSA'))`
      const exampleJoseKey = {
        crv: 'Ed25519',
        d: 'y71N3tdun63bo9OBHXuI03qaV3eY3kL1ypoG8tFy4LI',
        x: 'JOVEKqgcoSaDbYimIWoJHcvlZefVDQJXtKMmSRBHCHU',
        kty: 'OKP'
      }

      const keyPair = await Ed25519VerificationKey2020.fromJsonWebKey2020({
        type: 'JsonWebKey2020',
        publicKeyJwk: { ...exampleJoseKey },
        privateKeyJwk: { ...exampleJoseKey }
      })

      const exportedJwk: any = await keyPair.toJwk({
        publicKey: true,
        privateKey: true
      })

      expect(exportedJwk).toEqual({
        crv: 'Ed25519',
        d: 'y71N3tdun63bo9OBHXuI03qaV3eY3kL1ypoG8tFy4LI',
        x: 'JOVEKqgcoSaDbYimIWoJHcvlZefVDQJXtKMmSRBHCHU',
        kty: 'OKP'
      })

      const importedJoseKey = await jose.importJWK(exportedJwk, 'EdDSA')
      expect(await jose.exportJWK(importedJoseKey)).toEqual({
        crv: 'Ed25519',
        d: 'y71N3tdun63bo9OBHXuI03qaV3eY3kL1ypoG8tFy4LI',
        x: 'JOVEKqgcoSaDbYimIWoJHcvlZefVDQJXtKMmSRBHCHU',
        kty: 'OKP'
      })
    })
  })
})
